namespace tulo.eInvoice.eInvoiceApp.DTOs;

public class InvoicePositionDetailsDTO
{
    public Guid Id { get; set; }
    public int InvoicePositionNr { get; set; }

    #region Sub-position fields
    // Id of the parent GROUP position — null means top-level position
    public Guid? ParentPositionId { get; set; }

    // "GROUP"  → parent/summary line  (excluded from header tax calculation)
    // "DETAIL" → sub-position line    (linked to a GROUP via ParentPositionId)
    // ""       → normal standalone position
    public string LineStatusReasonCode { get; set; } = string.Empty;

    // Auto-generated by store/service:
    // top-level:    "01", "02", ...
    // sub-position: "0101", "0102", "0201", ...
    public string LineId { get; set; } = string.Empty;

    // Convenience — never set manually
    public bool IsGroupPosition => LineStatusReasonCode.Equals("GROUP", StringComparison.OrdinalIgnoreCase);

    public bool IsSubPosition => LineStatusReasonCode.Equals("DETAIL", StringComparison.OrdinalIgnoreCase);

    public bool IsStandalonePosition => !IsGroupPosition && !IsSubPosition;

    //example:
    //InvoicePositionNr=1  LineId="01"    LineStatusReasonCode="GROUP"   ParentPositionId=null
    //InvoicePositionNr=0  LineId="0101"  LineStatusReasonCode="DETAIL"  ParentPositionId=01-Guid
    //InvoicePositionNr = 0  LineId="0102"  LineStatusReasonCode="DETAIL"  ParentPositionId=01-Guid
    //InvoicePositionNr = 2  LineId="02"    LineStatusReasonCode=""         ParentPositionId=null  ← standalone
    #endregion

    public string InvoicePositionDescription { get; set; } = string.Empty;
    public string InvoicePositionProductDescription { get; set; } = string.Empty;
    public string InvoicePositionItemNr { get; set; } = string.Empty;
    public string InvoicePositionEan { get; set; } = string.Empty;

    public decimal InvoicePositionQuantity { get; set; }
    public string InvoicePostionUnit { get; set; } = string.Empty;

    public decimal InvoicePositionUnitPrice { get; set; }

    public int InvoicePositionVatRate { get; set; }
    public string InvoicePositionVatCategoryCode { get; set; } = string.Empty;

    public decimal InvoicePositionNetAmount { get; set; }
    public decimal InvoicePositionGrossAmount { get; set; }

    public string InvoicePositionDiscountReason { get; set; } = string.Empty;

    public decimal InvoicePositionDiscountNetAmount { get; set; }
    public decimal? InvoicePositionNetAmountAfterDiscount { get; set; }

    public DateOnly? InvoicePositionOrderDate { get; set; }
    public string InvoicePositionOrderId { get; set; } = string.Empty;

    public DateOnly? InvoicePositionDeliveryNoteDate { get; set; }
    public string InvoicePositionDeliveryNoteId { get; set; } = string.Empty;
    public string InvoicePositionDeliveryNoteLineId { get; set; } = string.Empty;

    public string InvoicePositionRefDocId { get; set; } = string.Empty;
    public string InvoicePositionRefDocType { get; set; } = string.Empty;
    public string InvoicePositionRefDocRefType { get; set; } = string.Empty;

    public object? InvoicePositionSelectedVatCategory { get; set; }
}
