name: Release tulo.eInvoiceApp

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-release:
    uses: ./.github/workflows/common-release.yml
    with:
      project_name: eInvoiceApp
      project_path: Src/WPF/eInvoiceApp/eInvoiceApp.csproj
      publish_dir: publish/tulo.eInvoiceApp
      zip_prefix: tulo.eInvoiceApp
      executable_name: tulo.eInvoiceApp.exe
      runtime: win-x64
      dotnet_version: 8.0.x
      config_file: NuGet.config
      prerelease: false